openapi: 3.0.0
info:
  contact:
    email: support@paloaltonetworks.com
    name: Palo Alto Networks Technical Support
    url: https://support.paloaltonetworks.com
  description: These APIs are used for Prisma Access and NGFW operations within Strata
    Cloud Manager.
  license:
    name: MIT
    url: https://opensource.org/license/mit
  termsOfService: https://www.paloaltonetworks.com/content/dam/pan/en_US/assets/pdf/legal/palo-alto-networks-end-user-license-agreement-eula.pdf
  title: Config Operations
  version: 2.0.0
servers:
- description: Current
  url: https://api.strata.paloaltonetworks.com/config/operations/v1
- description: Legacy
  url: https://api.sase.paloaltonetworks.com/sse/config/v1
security:
- scmToken: []
tags:
- description: Config Versions
  name: Config Versions
- description: Jobs
  name: Jobs
paths:
  /config-versions:
    get:
      description: |
        Retrieve a list of configuration versions.
      operationId: ListConfigVersions
      parameters:
      - description: The maximum number of results per page
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 200
          type: integer
        style: form
      - description: The offset into the list of results returned
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfigVersionsListResponse'
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: List configuration versions
      tags:
      - Config Versions
  /config-versions/candidate:
    delete:
      description: |
        Delete a candidate configuration.  Roll back to the running configuration.
      operationId: DeleteCandidateConfigVersions
      responses:
        "200":
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        "409":
          content:
            application/json:
              examples:
                name_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
                object_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
                reference_not_zero:
                  $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Conflict
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Delete a candidate configuration
      tags:
      - Config Versions
  /config-versions/candidate:push:
    post:
      description: |
        Push the candidate configuration.
      operationId: PushCandidateConfigVersions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PushCandidateConfigVersions_request'
        description: Created
      responses:
        "201":
          description: Created
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_object:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_object'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_body:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_body'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "409":
          content:
            application/json:
              examples:
                name_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
                object_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
                reference_not_zero:
                  $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Conflict
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Push the candidate configuration
      tags:
      - Config Versions
  /config-versions/running:
    get:
      description: |
        Get the running configuration versions on each folder.
      operationId: GetRunningConfigVersions
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/running-config-versions-response'
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Get running configuration versions
      tags:
      - Config Versions
  /config-versions/{version}:
    get:
      description: |
        Get config by version.
      operationId: GetConfigVersionsByID
      parameters:
      - description: The configuration version number
        explode: false
        in: path
        name: version
        required: true
        schema:
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/config-version'
                type: array
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Get config by version
      tags:
      - Config Versions
  /config-versions:load:
    post:
      description: |
        Load a specific configuration version into the candidate configuration.
      operationId: LoadConfigVersions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/load-config'
        description: Created
      responses:
        "201":
          description: Created
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_object:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_object'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_body:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_body'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "409":
          content:
            application/json:
              examples:
                name_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
                object_not_unique:
                  $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
                reference_not_zero:
                  $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Conflict
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Load config version
      tags:
      - Config Versions
  /jobs:
    get:
      description: |
        Retrieve a list of configuration jobs.
      operationId: ListJobs
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JobsListResponse'
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: List jobs
      tags:
      - Jobs
  /jobs/{id}:
    get:
      description: |
        Get an existing configuration job.
      operationId: GetJobsByID
      parameters:
      - description: The ID of the job
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobs-response'
          description: OK
        "400":
          content:
            application/json:
              examples:
                input_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
                invalid_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
                missing_query_parameter:
                  $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
                output_format_mismatch:
                  $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                auth_not_authenticated:
                  $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
                invalid_credential:
                  $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
                key_expired:
                  $ref: '#/components/examples/json_401_panui_auth_key_expired'
                key_too_long:
                  $ref: '#/components/examples/json_401_panui_auth_key_too_long'
                need_password_change:
                  $ref: '#/components/examples/json_401_panui_auth_need_password_change'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                auth_unauthorized:
                  $ref: '#/components/examples/json_403_panui_auth_unauthorized'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                object_not_present:
                  $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: Not Found
        default:
          content:
            application/json:
              examples:
                action_not_supported:
                  $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
                bad_xpath:
                  $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
                invalid_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
                malformed_command:
                  $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
                method_not_allowed:
                  $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
                session_timeout:
                  $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
                version_not_supported:
                  $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
              schema:
                $ref: '#/components/schemas/generic_error'
          description: General Errors
      summary: Get a job
      tags:
      - Jobs
components:
  examples:
    json_400_panui_mgmt_bad_xpath:
      summary: Bad XPath
      value:
        _errors:
        - code: E013
          details: {}
          message: Bad XPath
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_mgmt_invalid_command:
      summary: Invalid Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Command
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_mgmt_invalid_object:
      summary: Invalid Object
      value:
        _errors:
        - code: E003
          details: {}
          message: Invalid Object
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_mgmt_malformed_command:
      summary: Malformed Command
      value:
        _errors:
        - code: E003
          details: {}
          message: Malformed Command
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_restapi_input_format_mismatch:
      summary: Input Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: "Input Format Mismatch: input-format=json"
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_restapi_invalid_query_parameter:
      summary: Invalid Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: "Invalid Query Parameter: location=invalid"
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_restapi_missing_body:
      summary: Missing Body
      value:
        _errors:
        - code: E003
          details: {}
          message: Missing Body
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_restapi_missing_query_parameter:
      summary: Missing Query Parameter
      value:
        _errors:
        - code: E003
          details: {}
          message: "Missing Query Parameter: name"
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_400_panui_restapi_output_format_mismatch:
      summary: Output Format Mismatch
      value:
        _errors:
        - code: E003
          details: {}
          message: "Output Format Mismatch: output-format=json Accept=xml"
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_401_panui_auth_invalid_credential:
      summary: Invalid Credential
      value:
        _errors:
        - code: E016
          details: {}
          message: Invalid Credential
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_401_panui_auth_key_expired:
      summary: Key Expired
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Expired
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_401_panui_auth_key_too_long:
      summary: Key Too Long
      value:
        _errors:
        - code: E016
          details: {}
          message: Key Too Long
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_401_panui_auth_need_password_change:
      summary: Need Password Change
      value:
        _errors:
        - code: E016
          details: {}
          message: The password needs to be changed.
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_401_panui_auth_not_authenticated:
      summary: Not Authenticated
      value:
        _errors:
        - code: E016
          details: {}
          message: Not Authenticated
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_403_panui_auth_unauthorized:
      summary: Unauthorized
      value:
        _errors:
        - code: E007
          details: {}
          message: Unauthorized
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_404_panui_mgmt_object_not_present:
      summary: Object Not Present
      value:
        _errors:
        - code: E005
          details: {}
          message: Object Not Present
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_405_panui_restapi_action_not_supported:
      summary: Action Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: "Action Not Supported: move"
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_409_panui_mgmt_name_not_unique:
      summary: Name Not Unique
      value:
        _errors:
        - code: E006
          details: {}
          message: Name Not Unique
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_409_panui_mgmt_object_not_unique:
      summary: Object Not Unique
      value:
        _errors:
        - code: E016
          details: {}
          message: Object Not Unique
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_409_panui_mgmt_reference_not_zero:
      summary: Reference Not Zero
      value:
        _errors:
        - code: E009
          details: {}
          message: Reference Not Zero
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_501_panui_restapi_method_not_supported:
      summary: Method Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Method Not Supported
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_501_panui_restapi_version_not_supported:
      summary: Version Not Supported
      value:
        _errors:
        - code: E012
          details: {}
          message: Version Not Supported
        _request_id: 123e4567-e89b-12d3-a456-426655440000
    json_504_panui_mgmt_session_timeout:
      summary: Session Timeout
      value:
        _errors:
        - code: "4"
          details: {}
          message: Session Timeout
        _request_id: 123e4567-e89b-12d3-a456-426655440000
  parameters:
    jobid:
      description: The ID of the job
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
    limit:
      description: The maximum number of results per page
      explode: true
      in: query
      name: limit
      required: false
      schema:
        default: 200
        type: integer
      style: form
    offset:
      description: The offset into the list of results returned
      explode: true
      in: query
      name: offset
      required: false
      schema:
        default: 0
        type: integer
      style: form
    version:
      description: The configuration version number
      explode: false
      in: path
      name: version
      required: true
      schema:
        type: integer
      style: simple
  responses:
    access_errors:
      content:
        application/json:
          examples:
            auth_unauthorized:
              $ref: '#/components/examples/json_403_panui_auth_unauthorized'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Forbidden
    auth_errors:
      content:
        application/json:
          examples:
            auth_not_authenticated:
              $ref: '#/components/examples/json_401_panui_auth_not_authenticated'
            invalid_credential:
              $ref: '#/components/examples/json_401_panui_auth_invalid_credential'
            key_expired:
              $ref: '#/components/examples/json_401_panui_auth_key_expired'
            key_too_long:
              $ref: '#/components/examples/json_401_panui_auth_key_too_long'
            need_password_change:
              $ref: '#/components/examples/json_401_panui_auth_need_password_change'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Unauthorized
    bad_request_errors_basic:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    bad_request_errors_basic_with_body:
      content:
        application/json:
          examples:
            input_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_input_format_mismatch'
            invalid_object:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_object'
            invalid_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_invalid_query_parameter'
            missing_body:
              $ref: '#/components/examples/json_400_panui_restapi_missing_body'
            missing_query_parameter:
              $ref: '#/components/examples/json_400_panui_restapi_missing_query_parameter'
            output_format_mismatch:
              $ref: '#/components/examples/json_400_panui_restapi_output_format_mismatch'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Bad Request
    conflict_errors:
      content:
        application/json:
          examples:
            name_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_name_not_unique'
            object_not_unique:
              $ref: '#/components/examples/json_409_panui_mgmt_object_not_unique'
            reference_not_zero:
              $ref: '#/components/examples/json_409_panui_mgmt_reference_not_zero'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Conflict
    default_errors:
      content:
        application/json:
          examples:
            action_not_supported:
              $ref: '#/components/examples/json_405_panui_restapi_action_not_supported'
            bad_xpath:
              $ref: '#/components/examples/json_400_panui_mgmt_bad_xpath'
            invalid_command:
              $ref: '#/components/examples/json_400_panui_mgmt_invalid_command'
            malformed_command:
              $ref: '#/components/examples/json_400_panui_mgmt_malformed_command'
            method_not_allowed:
              $ref: '#/components/examples/json_501_panui_restapi_method_not_supported'
            session_timeout:
              $ref: '#/components/examples/json_504_panui_mgmt_session_timeout'
            version_not_supported:
              $ref: '#/components/examples/json_501_panui_restapi_version_not_supported'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: General Errors
    http_created:
      description: Created
    http_ok:
      description: OK
    not_found:
      content:
        application/json:
          examples:
            object_not_present:
              $ref: '#/components/examples/json_404_panui_mgmt_object_not_present'
          schema:
            $ref: '#/components/schemas/generic_error'
      description: Not Found
  schemas:
    ConfigVersionsListResponse:
      example:
        total: 1
        data:
        - "{}"
        - "{}"
        offset: 6
        limit: 0
      properties:
        data:
          items:
            $ref: '#/components/schemas/ConfigVersion'
          type: array
        limit:
          default: 200
          description: The maximum number of results per page
          type: integer
        offset:
          default: 0
          description: The offset into the list of results returned
          type: integer
        total:
          description: The total count of results
          type: integer
      required:
      - data
      - limit
      - offset
      - total
      type: object
    JobsListResponse:
      example:
        total: 1
        data:
        - "{}"
        - "{}"
        offset: 6
        limit: 0
      properties:
        data:
          items:
            $ref: '#/components/schemas/Jobs'
          type: array
        limit:
          default: 200
          description: The maximum number of results per page
          type: integer
        offset:
          default: 0
          description: The offset into the list of results returned
          type: integer
        total:
          description: The total count of results
          type: integer
      required:
      - data
      - limit
      - offset
      - total
      type: object
    config-version:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        types: types
        created: 0.8008281904610115
        admin: admin
        description: description
        ngfw_scope: ngfw_scope
        swg_config: swg_config
        version: version
        deleted: 6.027456183070403
        scope: scope
        id: 1
        impacted_devices: impacted_devices
        updated: 5.962133916683182
        edited_by: edited_by
      properties:
        admin:
          description: The administrator or service account that pushed this configuration
            version
          format: email
          type: string
        created:
          type: number
        date:
          format: date-time
          type: string
        deleted:
          type: number
        description:
          type: string
        edited_by:
          type: string
        id:
          description: The configuration version
          type: integer
        impacted_devices:
          type: string
        ngfw_scope:
          description: A comma separated list of firewall serial numbers
          type: string
        scope:
          type: string
        swg_config:
          type: string
        types:
          type: string
        updated:
          type: number
        version:
          description: The configuration version name
          type: string
      required:
      - admin
      - created
      - date
      - deleted
      - description
      - edited_by
      - id
      - impacted_devices
      - scope
      - types
      - updated
      - version
      type: object
    error_detail_cause_info:
      example:
        help: help
        code: code
        details: "{}"
        message: message
      properties:
        code:
          type: string
        details:
          type: object
        help:
          type: string
        message:
          type: string
      title: Cause Info
      type: object
    error_detail_cause_infos:
      items:
        $ref: '#/components/schemas/error_detail_cause_info'
      type: array
      x-examples: {}
    generic_error:
      example:
        _request_id: _request_id
        _errors:
        - help: help
          code: code
          details: "{}"
          message: message
        - help: help
          code: code
          details: "{}"
          message: message
      properties:
        _errors:
          items:
            $ref: '#/components/schemas/error_detail_cause_info'
          type: array
          x-examples: {}
        _request_id:
          type: string
      type: object
      x-examples: {}
    jobs:
      example:
        job_type: "53"
        result_str: OK
        start_ts: start_ts
        summary: summary
        uname: uname
        description: Added a new security rule for marketing
        status_str: ACT
        percent: percent
        job_status: "2"
        device_name: device_name
        end_ts: end_ts
        parent_id: "114"
        type_str: CommitAndPush
        details: "{\"errors\":[\"Config push aborted, error: Failed to handle VPN\
          \ clusters. Please check AutoVPN config for the device\"]}"
        job_result: "2"
        id: "115"
      properties:
        description:
          description: A description provided by the administrator or service account
          example: Added a new security rule for marketing
          type: string
        details:
          description: JSON string with detailed errors or info
          example: "{\"errors\":[\"Config push aborted, error: Failed to handle VPN\
            \ clusters. Please check AutoVPN config for the device\"]}"
          type: string
        device_name:
          description: The name of the device
          type: string
        end_ts:
          description: The timestamp indicating when the job was finished
          type: string
        id:
          description: The job ID
          example: "115"
          type: string
        job_result:
          description: The job result
          example: "2"
          type: string
        job_status:
          description: The current status of the job
          example: "2"
          type: string
        job_type:
          description: The job type
          example: "53"
          type: string
        parent_id:
          description: The parent job ID
          example: "114"
          type: string
        percent:
          description: Job completion percentage
          type: string
        result_str:
          description: The result of the job
          enum:
          - OK
          - FAIL
          - PEND
          - WAIT
          - CANCELLED
          - TIMEOUT
          type: string
        start_ts:
          description: The timestamp indicating when the job was created
          type: string
        status_str:
          description: The current status of the job
          enum:
          - ACT
          - FIN
          - PEND
          - PUSHSENT
          - PUSHFAIL
          - PUSHABORT
          - PUSHTIMEOUT
          type: string
        summary:
          description: The completion summary of the job
          type: string
        type_str:
          description: The job type
          enum:
          - CommitAll
          - CommitAndPush
          - NGFW-Bootstrap-Push
          - Validate
          example: CommitAndPush
          type: string
        uname:
          description: The administrator or service account that created the job
          format: email
          type: string
      required:
      - device_name
      - end_ts
      - id
      - job_result
      - job_status
      - job_type
      - parent_id
      - percent
      - result_str
      - start_ts
      - status_str
      - summary
      - type_str
      - uname
      type: object
    jobs-response:
      description: Response containing job data
      example:
        data:
        - job_type: "53"
          result_str: OK
          start_ts: start_ts
          summary: summary
          uname: uname
          description: Added a new security rule for marketing
          status_str: ACT
          percent: percent
          job_status: "2"
          device_name: device_name
          end_ts: end_ts
          parent_id: "114"
          type_str: CommitAndPush
          details: "{\"errors\":[\"Config push aborted, error: Failed to handle VPN\
            \ clusters. Please check AutoVPN config for the device\"]}"
          job_result: "2"
          id: "115"
        - job_type: "53"
          result_str: OK
          start_ts: start_ts
          summary: summary
          uname: uname
          description: Added a new security rule for marketing
          status_str: ACT
          percent: percent
          job_status: "2"
          device_name: device_name
          end_ts: end_ts
          parent_id: "114"
          type_str: CommitAndPush
          details: "{\"errors\":[\"Config push aborted, error: Failed to handle VPN\
            \ clusters. Please check AutoVPN config for the device\"]}"
          job_result: "2"
          id: "115"
      properties:
        data:
          items:
            $ref: '#/components/schemas/jobs'
          type: array
      type: object
    load-config:
      properties:
        version:
          type: integer
      type: object
    running-config-versions-response:
      description: Paginated response containing running configuration versions
      example:
        total: 5
        data:
        - date: 2000-01-23T04:56:07.000+00:00
          device: device
          version: 0
        - date: 2000-01-23T04:56:07.000+00:00
          device: device
          version: 0
        offset: 1
        limit: 6
      properties:
        data:
          items:
            $ref: '#/components/schemas/running-versions'
          type: array
        limit:
          type: integer
        offset:
          type: integer
        total:
          type: integer
      type: object
    running-versions:
      example:
        date: 2000-01-23T04:56:07.000+00:00
        device: device
        version: 0
      properties:
        date:
          description: The timestamp of when the configuration version was pushed
            to the folder or firewall
          format: date-time
          type: string
        device:
          description: The folder name or firewall serial number
          type: string
        version:
          description: The configuration version number
          type: integer
      required:
      - date
      - device
      - version
      type: object
    PushCandidateConfigVersions_request:
      properties:
        admin:
          description: "List the administrators and/or service accounts in this field.\
            \ If you want to push folder named All, please do not add this admin field\
            \ at all and list each of the folders under All in the folder field."
          items:
            type: string
          type: array
        description:
          description: A description of the changes being pushed
          type: string
        devices:
          description: The target devices for the configuration push
          example:
          - 7951000388704
          - 7951000388707
          - 7051000239252
          items:
            maxLength: 16
            type: number
          type: array
          uniqueItems: true
        folder:
          description: The target folders for the configuration push
          example:
          - Prisma Access
          - Mobile Users
          - Service Conncetions
          items:
            maxLength: 64
            pattern: "^[a-zA-Z\\d-_\\. ]+$"
            type: string
          type: array
          uniqueItems: true
      required:
      - folders
      - folders
      type: object
  securitySchemes:
    scmOAuth:
      description: "Strata Cloud Manager APIs authenticate client requests using the\
        \ \nOAuth 2.0 Client Credentials flow.  Please use the `client_id`, \n`client_secret`\
        \ values associated with an IAM service account along \nwith a scope value\
        \ of `tsg_id:XXXXXXXXXX`, where `XXXXXXXXXX` is the \nTenant Service Group\
        \ (TSG) ID.  The resulting JWT access token should \nbe attached to all API\
        \ calls as a `Bearer` token in the `Authorization` \nheader (ex. `Authorization:\
        \ Bearer tokenstring`).\n"
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.apps.paloaltonetworks.com/oauth2/access_token
      type: oauth2
    scmToken:
      bearerFormat: JWT
      description: "Strata Cloud Manager APIs authenticate client requests using the\
        \ \nOAuth 2.0 Client Credentials flow.  Please use the `client_id`, \n`client_secret`\
        \ values associated with an IAM service account along \nwith a scope value\
        \ of `tsg_id:XXXXXXXXXX`, where `XXXXXXXXXX` is the \nTenant Service Group\
        \ (TSG) ID.  The resulting JWT access token should \nbe attached to all API\
        \ calls as a `Bearer` token in the `Authorization` \nheader (ex. `Authorization:\
        \ Bearer tokenstring`).\n"
      scheme: bearer
      type: http
x-internal: false
